// Code generated by MockGen. DO NOT EDIT.
// Source: security/service/user_management.go
//
// Generated by this command:
//
//	mockgen -source=security/service/user_management.go -destination=mocks/mock_security_service_user_management.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Drathveloper/go-web-skeleton/common/domain"
	domain0 "github.com/Drathveloper/go-web-skeleton/security/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserManagementRepository is a mock of UserManagementRepository interface.
type MockUserManagementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagementRepositoryMockRecorder
	isgomock struct{}
}

// MockUserManagementRepositoryMockRecorder is the mock recorder for MockUserManagementRepository.
type MockUserManagementRepositoryMockRecorder struct {
	mock *MockUserManagementRepository
}

// NewMockUserManagementRepository creates a new mock instance.
func NewMockUserManagementRepository(ctrl *gomock.Controller) *MockUserManagementRepository {
	mock := &MockUserManagementRepository{ctrl: ctrl}
	mock.recorder = &MockUserManagementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManagementRepository) EXPECT() *MockUserManagementRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserManagementRepository) CreateUser(ctx context.Context, user *domain0.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserManagementRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserManagementRepository)(nil).CreateUser), ctx, user)
}

// FindAllUserLookups mocks base method.
func (m *MockUserManagementRepository) FindAllUserLookups(ctx context.Context) ([]domain0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllUserLookups", ctx)
	ret0, _ := ret[0].([]domain0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllUserLookups indicates an expected call of FindAllUserLookups.
func (mr *MockUserManagementRepositoryMockRecorder) FindAllUserLookups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllUserLookups", reflect.TypeOf((*MockUserManagementRepository)(nil).FindAllUserLookups), ctx)
}

// FindAllUsers mocks base method.
func (m *MockUserManagementRepository) FindAllUsers(ctx context.Context, pagination *domain.Pagination) ([]domain0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllUsers", ctx, pagination)
	ret0, _ := ret[0].([]domain0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllUsers indicates an expected call of FindAllUsers.
func (mr *MockUserManagementRepositoryMockRecorder) FindAllUsers(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllUsers", reflect.TypeOf((*MockUserManagementRepository)(nil).FindAllUsers), ctx, pagination)
}

// FindUserByID mocks base method.
func (m *MockUserManagementRepository) FindUserByID(ctx context.Context, id uint) (*domain0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", ctx, id)
	ret0, _ := ret[0].(*domain0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockUserManagementRepositoryMockRecorder) FindUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockUserManagementRepository)(nil).FindUserByID), ctx, id)
}

// UpdateUser mocks base method.
func (m *MockUserManagementRepository) UpdateUser(ctx context.Context, user *domain0.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserManagementRepositoryMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserManagementRepository)(nil).UpdateUser), ctx, user)
}
