// Code generated by MockGen. DO NOT EDIT.
// Source: common/http/middleware/session.go
//
// Generated by this command:
//
//	mockgen -source=common/http/middleware/session.go -destination=mocks/mock_common_middleware_session.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Drathveloper/go-web-skeleton/common/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// CreateAnonymousSession mocks base method.
func (m *MockSessionService) CreateAnonymousSession(ctx context.Context, sessionID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnonymousSession", ctx, sessionID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAnonymousSession indicates an expected call of CreateAnonymousSession.
func (mr *MockSessionServiceMockRecorder) CreateAnonymousSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnonymousSession", reflect.TypeOf((*MockSessionService)(nil).CreateAnonymousSession), ctx, sessionID)
}

// LoadSession mocks base method.
func (m *MockSessionService) LoadSession(ctx context.Context, sessionID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSession", ctx, sessionID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSession indicates an expected call of LoadSession.
func (mr *MockSessionServiceMockRecorder) LoadSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSession", reflect.TypeOf((*MockSessionService)(nil).LoadSession), ctx, sessionID)
}

// UpdateSession mocks base method.
func (m *MockSessionService) UpdateSession(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockSessionServiceMockRecorder) UpdateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockSessionService)(nil).UpdateSession), ctx, session)
}

// MockSessionConfigProvider is a mock of SessionConfigProvider interface.
type MockSessionConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSessionConfigProviderMockRecorder
	isgomock struct{}
}

// MockSessionConfigProviderMockRecorder is the mock recorder for MockSessionConfigProvider.
type MockSessionConfigProviderMockRecorder struct {
	mock *MockSessionConfigProvider
}

// NewMockSessionConfigProvider creates a new mock instance.
func NewMockSessionConfigProvider(ctrl *gomock.Controller) *MockSessionConfigProvider {
	mock := &MockSessionConfigProvider{ctrl: ctrl}
	mock.recorder = &MockSessionConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionConfigProvider) EXPECT() *MockSessionConfigProviderMockRecorder {
	return m.recorder
}

// GetCookieDomain mocks base method.
func (m *MockSessionConfigProvider) GetCookieDomain() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCookieDomain")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCookieDomain indicates an expected call of GetCookieDomain.
func (mr *MockSessionConfigProviderMockRecorder) GetCookieDomain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCookieDomain", reflect.TypeOf((*MockSessionConfigProvider)(nil).GetCookieDomain))
}

// GetSessionTTL mocks base method.
func (m *MockSessionConfigProvider) GetSessionTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetSessionTTL indicates an expected call of GetSessionTTL.
func (mr *MockSessionConfigProviderMockRecorder) GetSessionTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionTTL", reflect.TypeOf((*MockSessionConfigProvider)(nil).GetSessionTTL))
}

// IsSecureCookie mocks base method.
func (m *MockSessionConfigProvider) IsSecureCookie() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSecureCookie")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSecureCookie indicates an expected call of IsSecureCookie.
func (mr *MockSessionConfigProviderMockRecorder) IsSecureCookie() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSecureCookie", reflect.TypeOf((*MockSessionConfigProvider)(nil).IsSecureCookie))
}
