// Code generated by MockGen. DO NOT EDIT.
// Source: security/repository/redis/session.go
//
// Generated by this command:
//
//	mockgen -source=security/repository/redis/session.go -destination=mocks/mock_security_repository_redis_session.go -package=mocks -mock_names=SessionConfigProvider=MockRedisSessionConfigProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRedisSessionConfigProvider is a mock of SessionConfigProvider interface.
type MockRedisSessionConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRedisSessionConfigProviderMockRecorder
	isgomock struct{}
}

// MockRedisSessionConfigProviderMockRecorder is the mock recorder for MockRedisSessionConfigProvider.
type MockRedisSessionConfigProviderMockRecorder struct {
	mock *MockRedisSessionConfigProvider
}

// NewMockRedisSessionConfigProvider creates a new mock instance.
func NewMockRedisSessionConfigProvider(ctrl *gomock.Controller) *MockRedisSessionConfigProvider {
	mock := &MockRedisSessionConfigProvider{ctrl: ctrl}
	mock.recorder = &MockRedisSessionConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisSessionConfigProvider) EXPECT() *MockRedisSessionConfigProviderMockRecorder {
	return m.recorder
}

// GetSessionTTL mocks base method.
func (m *MockRedisSessionConfigProvider) GetSessionTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetSessionTTL indicates an expected call of GetSessionTTL.
func (mr *MockRedisSessionConfigProviderMockRecorder) GetSessionTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionTTL", reflect.TypeOf((*MockRedisSessionConfigProvider)(nil).GetSessionTTL))
}
